version: "2"
linters:
  default: all
  disable:
    # Too strict.
    - cyclop # redundant, covered by gocyclo
    - depguard
    - exhaustruct
    - funcorder # new, too much to move around
    - nestif # redundant, covered by gocyclo
    - nlreturn
    - testpackage
    - varnamelen
    - wsl
  settings:
    errcheck:
      disable-default-exclusions: false
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 68
      ignore-comments: true
    gocognit:
      min-complexity: 32
  exclusions:
    generated: lax
    rules:
      # Exclude some linters from running on tests files.
      - linters:
          - err113
          - funlen
          - maintidx
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
